default: true
MD013:
  line_length: 140
  heading_line_length: 120
  code_block_line_length: 0
  tables: false

MD025:
  front_matter_title: false

MD026:
  punctuation: ".,;:"

MD033:
  allowed_elements:
    - br
    - img
    - details
    - summary
    - span
    - div